config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tasks#index"
  resources :tasks do
    member do
      put :completed
      put :uncompleted
    end
  end
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates_presence_of :title
    
    PRIORITIES = [
        [1],
        [2],
        [3]
    ]
    def complete!
        self.completed = true
        save
    end
    def uncomplete!
        self.completed = false
        save
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    if user_signed_in?
      @tasks = Task.where(:user_id => current_user.id, completed: false)
      @completed_tasks = Task.where(:user_id => current_user.id, completed: true)
    end
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def completed
    @task = Task.find(params[:id])
    @task.complete!
    redirect_to root_path
  end
  def uncompleted
    @task = Task.find(params[:id])
    @task.uncomplete!
    redirect_to root_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :descriprion, :priority, :due, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <div>
          <%= link_to "My Tasks", tasks_path ,class: 'navbar-brand' %>
          <% if user_signed_in? %>
            <%= link_to "Create Task", new_task_path, class: 'navbar-text' %>
        <% end %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user.present? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li class="pr-3"><%= link_to "Sign In", new_user_session_path %>
            </li>
            <li><%= link_to "Sign Up", new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :descriprion %>
    <%= form.text_area :descriprion, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :priority %>
    <%= form.select :priority, Task::PRIORITIES %>
  </div>

  <div class="form-group">
    <%= form.label :due %>
    <%= form.date_select :due %>
  </div>

  <div class="form-group">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>
<div class="mt-2 text-right">
    <%= link_to 'Show', @task, class: "btn btn-primary" %> 
    <%= link_to 'Back', tasks_path, class: "btn btn-primary" %>
</div>

app/views/tasks/index.html.erb
<% if user_signed_in? %>
  <div class="card">
    <div class="card_body">
    <h1 class="card-title mb-4 mt-4">Tasks</h1> 
      <hr>
      <div class="task">
        <% @tasks.each do |task| %>
          <div class="task-item">
            <p>      
              <span class="title pr-2"><%= link_to task.title, task %></span>
              <span class="pr-2"><%= link_to 'New Task', new_task_path, class: 'action btn btn-primary' %></span> 
              <span class="pr-2"><%= link_to 'Edit', edit_task_path(task), class: 'action btn btn-primary' %></span>
              <span class="pr-2"><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'action btn btn-primary' %></span>
              <span class="pr-2"><%= link_to 'Completed',completed_task_path(task), data: {method: :put}, class: 'action btn btn-primary' %></span>
            </p>
          </div>                  
        <% end %>
      </div>
    

  <hr>
      <div class="task">
        <% @completed_tasks.each do |task| %>
          <div class="task-item">
            <p> 
              <span class="title completed pr-2"><%= link_to task.title, task %></span>
              <span class="pr-2"><%= link_to 'New Task', new_task_path, class: 'action btn btn-primary' %></span> 
              <span class="pr-2"><%= link_to 'Edit', edit_task_path(task), class: 'action btn btn-primary' %></span>
              <span class="pr-2"><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'action btn btn-primary' %></span>
             <span class="pr-2"><%= link_to 'Uncompleted',uncompleted_task_path(task), data: {method: :put}, class: 'action btn btn-primary' %></span>  
            </p>
          </div>              
        <% end %>
      </div>
    </div>   
  </div>
<% end %>

app/views/tasks/new.html.erb
<h1 class="space-between">New Task
<%= link_to 'Back', tasks_path, class: 'btn btn-primary'%>
</h1>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<%= link_to 'Back', tasks_path, class: "btn btn-primary" %>
<h4>
  <%= @task.title %>
</h4>

<p>
  <%= @task.descriprion %>
</p>
<div class="space-between">
<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>
<p>
  <strong>Due:</strong>
  <%= @task.due %>
</p>
</div>
<%= link_to 'Edit', edit_task_path(@task), class: "btn btn-primary" %> 